version: '4'

services:
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: papi
    volumes:
      - db-volume:/var/lib/postgresql/data

  api:
    image: jlfaguiar/ac2devops:latest
    networks:
      - default  # Certifique-se de que está usando a rede adequada
    environment:
      DB_HOST: database
    ports:
      - "8686:8080"
    command: ["java", "-jar", "ac2-0.0.1-SNAPSHOT.jar"]
volumes:
  db-volume: